<?php
//--------------------------------------------------------------------------//
/** @var \Magento\Framework\Session\Config\ConfigInterface $sessionConfig */
$sessionConfig = \Magento\Framework\App\ObjectManager::getInstance()->get(
    \Magento\Framework\Session\Config\ConfigInterface::class
);
//--------------------------------------------------------------------------//
$sameSite = 'None';
/** @var $block \Magento\Framework\View\Element\Js\Cookie */
?>
<script type="text/x-magento-init">
{
    "*": {
        "mage/cookies": {
            "expires": null,
            "path": "<?= $block->escapeJs($block->getPath()) ?>",
            "domain": "<?= $block->escapeJs($block->getDomain()) ?>",
            "secure": true,
            "lifetime": "<?= $block->escapeJs($block->getLifetime()) ?>",
            "samesite": "<?= $sameSite ?>"
        }
    }
}</script>
