<?php
//--------------------------------------------------------------------------//
/** @var \Magento\Framework\Session\Config\ConfigInterface $sessionConfig */
$sessionConfig = \Magento\Framework\App\ObjectManager::getInstance()->get(
    \Magento\Framework\Session\Config\ConfigInterface::class
);
//--------------------------------------------------------------------------//
?>
<?php /** * Copyright © Magento, Inc. All rights reserved. * See COPYING.txt for license details. */ /** * Cookie settings initialization script * * @var $block \Magento\Framework\View\Element\Js\Cookie */ ?> <script type="text/x-magento-init">
    {
        "*": {
            "mage/cookies": {
                "expires": null,
                "path": "<?= $block->escapeJs($block->getPath()) ?>",
                "domain": "<?= $block->escapeJs($block->getDomain()) ?>",
                "secure": <?= $sessionConfig->getCookieSecure() ? 'true' : 'false' ?>,
                "lifetime": "<?= $block->escapeJs($block->getLifetime()) ?>"
            }
        }
    }</script>
