<?php
//--------------------------------------------------------------------------//
/** @var \Magento\Framework\Session\Config\ConfigInterface $sessionConfig */
$sessionConfig = \Magento\Framework\App\ObjectManager::getInstance()->get(
    \Magento\Framework\Session\Config\ConfigInterface::class
);
//--------------------------------------------------------------------------//
/**
 * Cookie settings initialization script
 *
 * @var $block \Magento\Framework\View\Element\Js\Cookie
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$isCookieSecure = $sessionConfig->getCookieSecure() ? 'true' : 'false';
$sameSite = 'None';
$scriptString = "
    window.cookiesConfig = window.cookiesConfig || {};
    window.cookiesConfig.secure = $isCookieSecure;
    window.cookiesConfig.samesite = '$sameSite';
";
?>
<?php if (isset($secureRenderer)): //check for older versions ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
